# Generated by Django 3.2.19 on 2023-07-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='root_de_la_empresa',
            new_name='rut_de_la_empresa',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='root_del_empleado',
            new_name='rut_del_empleado',
        ),
    ]
