# Generated by Django 3.2.19 on 2023-07-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20230703_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut_del_empleado',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
