# Generated by Django 3.2.19 on 2023-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_customuser_rut_del_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='baika', max_length=100),
            preserve_default=False,
        ),
    ]
